name: CI
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Multipass Frontend | install
        run: yarn
      - name: Multipass Frontend | Run minimal checks
        run: yarn build

      - name: Multipass Demo | install
        run: cd examples/MultipassDemo && yarn
      - name: Multipass Demo | Run minimal checks
        run: cd examples/MultipassDemo && yarn build
