name: Deployment
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: BACKEND | write identity pem
        run: |
          mkdir -p $ID_PATH
          echo $GH_MP_ADMIN_PEM >> $ID_PATH/identity.pem
          sed -i 's/\\r\\n/\r\n/g' $ID_PATH/identity.pem
        shell: bash
        env:
          GH_MP_ADMIN_PEM: ${{secrets.GH_MP_ADMIN_PEM}}
          ID_PATH: /home/runner/.config/dfx/identity/gh_mp_admin

      - name: Echo pem
        run: cat $ID_PATH/identity.pem
        env:
          ID_PATH: /home/runner/.config/dfx/identity/gh_mp_admin

      - name: BACKEND | Provision Linux
        run: bash .github/workflows/dfx-provision-linux.sh

      - name: MULTIPASS FRONTEND | Install
        run: yarn

      - name: MULTIPASS FRONTEND | Deploy to production
        run: |
          dfx identity use gh_mp_admin
          dfx deploy --network ic --no-wallet
        env:
          VITE_II_CANISTER_ID: ${{secrets.VITE_II_CANISTER_ID}}
          VITE_II_ENV: ${{secrets.VITE_II_ENV}}
          VITE_MULTIPASS_DOMAIN: ${{secrets.VITE_II_ENVVITE_II_ENV}}

      - name: MULTIPASS DEMO | Install
        run: |
          cd examples/MultipassDemo && yarn
          dfx identity use gh_mp_admin
          dfx start --clean --background
          dfx deploy --no-wallet
          dfx stop

      - name: MULTIPASS FRONTEND | Deploy to production
        run: |
          cd examples/MultipassDemo
          dfx identity use gh_mp_admin
          dfx deploy --network ic --no-wallet
        env:
          DFX_NETWORK: ${{secrets.DFX_NETWORK}}
          MULTIPASS_FRONTEND_DOMAIN: ${{secrets.MULTIPASS_FRONTEND_DOMAIN}}
          NEXT_PUBLIC_IC_HOST: ${{secrets.NEXT_PUBLIC_IC_HOST}}
