name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: DFX SETUP | write identity pem
        run: |
          mkdir -p $ID_PATH
          echo $GH_MP_ADMIN_PEM >> $ID_PATH/identity.pem
          sed -i 's/\\r\\n/\r\n/g' $ID_PATH/identity.pem
        shell: bash
        env:
          GH_MP_ADMIN_PEM: ${{secrets.GH_MP_ADMIN_PEM}}
          ID_PATH: /home/runner/.config/dfx/identity/gh_mp_admin

      - name: DFX SETUP  | Provision Linux
        run: bash .github/workflows/dfx-provision-linux.sh

      - name: MULTIPASS FRONTEND | deploy
        run: |
          yarn

          network="ic"
          if [[ ${GITHUB_REF} != "refs/heads/main" ]]; then
            network="local"
            dfx start --clean --background
          fi

          dfx identity use gh_mp_admin
          dfx deploy --network $network --no-wallet

          if [[ ${GITHUB_REF} != "refs/heads/main" ]]; then
            dfx stop
          fi
        env:
          VITE_MP_CANISTER_ID: ${{secrets.VITE_MP_CANISTER_ID}}
          VITE_II_CANISTER_ID: ${{secrets.VITE_II_CANISTER_ID}}
          VITE_II_ENV: ${{secrets.VITE_II_ENV}}
          VITE_MULTIPASS_DOMAIN: ${{secrets.VITE_MULTIPASS_DOMAIN}}

      - name: MULTIPASS Demo | deploy
        run: |
          cd examples/MultipassDemo && yarn

          network="ic"
          if [[ ${GITHUB_REF} != "refs/heads/main" ]]; then
            network="local"
            dfx start --clean --background
          fi

          dfx identity use gh_mp_admin
          dfx deploy --network $network --no-wallet

          if [[ ${GITHUB_REF} != "refs/heads/main" ]]; then
            dfx stop
          fi
        env:
          DFX_NETWORK: ${{secrets.DFX_NETWORK}}
          NEXT_PUBLIC_MP_ID_PROVIDER_URL: ${{secrets.NEXT_PUBLIC_MP_ID_PROVIDER_URL}}
          NEXT_PUBLIC_IC_HOST: ${{secrets.NEXT_PUBLIC_IC_HOST}}
