name: Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.4
        env:
          DFX_IDENTITY_PEM: ${{ secrets.GH_MP_ADMIN_PEM }}

      - name: MULTIPASS FRONTEND | install & deploy
        run: |
          yarn && yarn

          # install local to generate the types
          dfx start --clean --background
          dfx deploy --no-wallet
          dfx stop

          pushd frontend/ui-kit
          yarn && yarn build
          popd

          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            dfx identity use action
            dfx deploy --network ic  --no-wallet
          fi

        env:
          VITE_IDENTITY_MANAGER_CANISTER_ID: ${{secrets.VITE_IDENTITY_MANAGER_CANISTER_ID}}
          VITE_PUB_SUB_CHANNEL_CANISTER_ID: ${{secrets.VITE_PUB_SUB_CHANNEL_CANISTER_ID}}
          VITE_II_CANISTER_ID: ${{secrets.VITE_II_CANISTER_ID}}
          VITE_II_ENV: ${{secrets.VITE_II_ENV}}
          VITE_MULTIPASS_DOMAIN: ${{secrets.VITE_MULTIPASS_DOMAIN}}
          VITE_AWS_VERIFY_PHONENUMBER: ${{secrets.VITE_AWS_VERIFY_PHONENUMBER}}

      - name: MULTIPASS Demo | install & deploy
        run: |
          cd examples/MultipassDemo && yarn

          # install local to generate the types
          dfx start --clean --background
          dfx deploy --no-wallet
          dfx stop

          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            dfx identity use action
            dfx deploy --network ic  --no-wallet
          fi

        env:
          DFX_NETWORK: ${{secrets.DFX_NETWORK}}
          NEXT_PUBLIC_MP_ID_PROVIDER_URL: ${{secrets.NEXT_PUBLIC_MP_ID_PROVIDER_URL}}
          NEXT_PUBLIC_IC_HOST: ${{secrets.NEXT_PUBLIC_IC_HOST}}
